# Generated by Django 4.1.1 on 2022-09-25 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='', max_length=300)),
                ('active', models.BooleanField(default=False)),
                ('notes', models.TextField(max_length=4000)),
            ],
        ),
    ]
